name: Run CI checks

on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0"

      - name: set version string
        run: |
          echo "(devel)" > cmd/VERSION

      - name: Linting etc
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47
          args: --timeout 5m0s

      - name: Run tests
        run: |
          make test
          go tool cover -func coverage.out | grep total
