name: Run CI checks

on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Run tests
        run: |
          go test ./...

      - name: Linting etc
        run: |
          go get -u golang.org/x/lint/golint
          make lint vet
